---
caching:
  expires: 3600
db:
  fb_201505:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp
  fb_201604:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_mirror
  fb_201703:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201703
  fb_201712:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201712
  fb_201809:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201809
  fb_201901:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201901
  fb_201902:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201902
  fb_201904:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201904
  fb_201908:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201908
  fb_201912:
    adapter: mysql2
    encoding: utf8
    host: fishbase
    username: root
    password: root
    port: 3306
    database: fbapp_201912
  slb_201712:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201712
  slb_201809:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201809
  slb_201901:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201901
  slb_201902:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201902
  slb_201904:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201904
  slb_201908:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201908
  slb_201912:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201912
